apiVersion: v1
kind: Service
metadata:
  labels:
    service: pubsub-service
  name: pubsub-service
  namespace: default
spec:
  ports:
  - name: ssl
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    service: pubsub-push-model
  sessionAffinity: None
  type: LoadBalancer